/*
 * Instaclustr Cassandra Sidecar
 *
 * REST API for Cassandra Sidecar from Instaclustr
 *
 * API version: 1.1.0
 * Contact: support@instaclustr.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package cassandrasidecar
import (
	"time"
)
// SidecarVersion struct for SidecarVersion
type SidecarVersion struct {
	// textual representation of Sidecar version
	Version string `json:"version,omitempty"`
	// timestamp this Sidecar was built
	BuildTime time.Time `json:"buildTime,omitempty"`
	// git commit hash this Sidecar was built from
	GitCommit string `json:"gitCommit,omitempty"`
}
