/*
 * Instaclustr Cassandra Sidecar
 *
 * REST API for Cassandra Sidecar from Instaclustr
 *
 * API version: 1.1.0
 * Contact: support@instaclustr.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package cassandrasidecar
// TokenRange struct for TokenRange
type TokenRange struct {
	// starting token of a range 
	Start string `json:"start"`
	// ending token of a range 
	End string `json:"end"`
}
