/*
 * Instaclustr Cassandra Sidecar
 *
 * REST API for Cassandra Sidecar from Instaclustr
 *
 * API version: 1.1.0
 * Contact: support@instaclustr.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package cassandrasidecar
// TruncateOperationRequest struct for TruncateOperationRequest
type TruncateOperationRequest struct {
	Type string `json:"type"`
	// keyspace to truncate
	Keyspace string `json:"keyspace"`
	// table to truncate
	Table string `json:"table"`
}
