/*
 * Instaclustr Cassandra Sidecar
 *
 * REST API for Cassandra Sidecar from Instaclustr
 *
 * API version: 1.1.0
 * Contact: support@instaclustr.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package cassandrasidecar
// FlushOperationRequest flushes tables of a keyspace or all tables of a keyspace when tables are not specified 
type FlushOperationRequest struct {
	Type string `json:"type"`
	// keyspace to flush 
	Keyspace string `json:"keyspace"`
	// tables to flush, if not provided or empty, flush all tables in a keyspace 
	Tables []string `json:"tables,omitempty"`
}
