/*
 * Instaclustr Cassandra Sidecar
 *
 * REST API for Cassandra Sidecar from Instaclustr
 *
 * API version: 1.1.0
 * Contact: support@instaclustr.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package cassandrasidecar
// CassandraSchemaVersionException struct for CassandraSchemaVersionException
type CassandraSchemaVersionException struct {
	Exception map[string]interface{} `json:"exception,omitempty"`
}
