/*
 * Instaclustr Cassandra Sidecar
 *
 * REST API for Cassandra Sidecar from Instaclustr
 *
 * API version: 1.1.0
 * Contact: support@instaclustr.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package cassandrasidecar

type OneOfbody struct {
    CleanupOperationRequest
    DecommissionOperationRequest
    DrainOperationRequest
    FlushOperationRequest
    RebuildOperationRequest
    RefreshOperationRequest
    RestartOperationRequest
    ScrubOperationRequest
    UpgradeSsTablesOperationRequest
    ImportOperationRequest
    TruncateOperationRequest
    BackupOperationRequest
    RestoreOperationRequest
}
