/*
 * Instaclustr Cassandra Sidecar
 *
 * REST API for Cassandra Sidecar from Instaclustr
 *
 * API version: 1.1.0
 * Contact: support@instaclustr.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package cassandrasidecar
// CassandraSchemaVersion struct for CassandraSchemaVersion
type CassandraSchemaVersion struct {
	// UUID representing a version of Cassandra node as reported by its StorageServiceMBean#getSchemaVersion
	SchemaVersion string `json:"schemaVersion,omitempty"`
}
