/*
 * Instaclustr Cassandra Sidecar
 *
 * REST API for Cassandra Sidecar from Instaclustr
 *
 * API version: 1.1.0
 * Contact: support@instaclustr.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package cassandrasidecar
// RefreshOperationRequest refreshes a table, this is done by calling StorageServiceMBean#loadNewSSTables 
type RefreshOperationRequest struct {
	Type string `json:"type"`
	// keyspace to refresh 
	Keyspace string `json:"keyspace"`
	// table to refresh 
	Table string `json:"table"`
}
