/*
 * Instaclustr Cassandra Sidecar
 *
 * REST API for Cassandra Sidecar from Instaclustr
 *
 * API version: 1.1.0
 * Contact: support@instaclustr.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package cassandrasidecar

type CassandraStatus struct {
	// State of a Cassandra node as reported from StorageServiceMBean#getOperationMode
	NodeState string `json:"nodeState,omitempty"`
}
